POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2MWI4YWU4NjUyOGQ3ZWYxYjE1YTU2NjUiLCJpYXQiOjE2NDAwNDQ2MzN9.spoTfvgqJ3OUZW7u_ED4nqyirxhW3l3isY1-UkIvkeI

{
    "title": "Testing 123",
    "author": "Yo Man",
    "url": "https://fullstackopen.com",
    "likes": 12
}